version: '3'
services:
  nginx:
    container_name: servermanager
    networks:
      nginx_default:
    image: nginx
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../SummonerExpert/nginx.conf:/etc/nginx/sites-enabled/summonerexpert.conf
      - ../SupermarKit/nginx.conf:/etc/nginx/sites-enabled/supermarkit.conf
      - ../danReynolds.ca/nginx.conf:/etc/nginx/sites-enabled/danreynolds.conf
      - /etc/letsencrypt/live:/etc/nginx/certs/
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/certs/dhparam.pem
    ports:
      - 80:80
      - 443:443
volumes:
  logs:
networks:
  nginx_default:
    external: true
