version: '3'
services:
  nginx:
    networks:
      nginx_default:
    image: nginx
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../SupermarKit/nginx.conf:/etc/nginx/sites-enabled/supermarkit.conf
      - ../danReynolds.ca/nginx.conf:/etc/nginx/sites-enabled/danreynolds.conf
      - /etc/letsencrypt/live/supermarkit.org/fullchain.pem:/etc/nginx/certs/supermarkit_fullchain.pem
      - /etc/letsencrypt/live/supermarkit.org/privkey.pem:/etc/nginx/certs/supermarkit_privkey.pem
      - /etc/letsencrypt/live/supermarkit.org/chain.pem:/etc/nginx/certs/supermarkit_chain.pem
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/certs/dhparam.pem
    ports:
      - 80:80
      - 443:443
volumes:
  logs:
networks:
  nginx_default:
    external: true
