version: '3'
services:
  nginx:
    container_name: servermanager
    networks:
      nginx_default:
    image: nginx
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../SummonerExpert/nginx.conf:/etc/nginx/sites-enabled/summonerexpert.conf
      - ../SummonerExpert-Client/nginx.conf:/etc/nginx/sites-enabled/summonerexpert-client.conf
      - ../SupermarKit/nginx.conf:/etc/nginx/sites-enabled/supermarkit.conf
      - ../danReynolds.ca/nginx.conf:/etc/nginx/sites-enabled/danreynolds.conf
      - /etc/letsencrypt/live/danreynolds.ca/privkey.pem:/etc/nginx/certs/danreynolds.ca_privkey.pem
      - /etc/letsencrypt/live/danreynolds.ca/chain.pem:/etc/nginx/certs/danreynolds.ca_chain.pem
      - /etc/letsencrypt/live/danreynolds.ca/fullchain.pem:/etc/nginx/certs/danreynolds.ca_fullchain.pem
      - /etc/letsencrypt/live/supermarkit.org/privkey.pem:/etc/nginx/certs/supermarkit_privkey.pem
      - /etc/letsencrypt/live/supermarkit.org/chain.pem:/etc/nginx/certs/supermarkit_chain.pem
      - /etc/letsencrypt/live/supermarkit.org/fullchain.pem:/etc/nginx/certs/supermarkit_fullchain.pem
      - /etc/letsencrypt/live/api.summonerexpert.com/privkey.pem:/etc/nginx/certs/summonerexpert_privkey.pem
      - /etc/letsencrypt/live/api.summonerexpert.com/chain.pem:/etc/nginx/certs/summonerexpert_chain.pem
      - /etc/letsencrypt/live/api.summonerexpert.com/fullchain.pem:/etc/nginx/certs/summonerexpert_fullchain.pem
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/certs/dhparam.pem
    ports:
      - 80:80
      - 443:443
volumes:
  logs:
networks:
  nginx_default:
    external: true
