version: '3'
services:
  letsencrypt:
    image: certbot/certbot:latest
    volumes:
      - webroot:/usr/share/nginx/html
      - letsencrypt:/etc/letsencrypt
  nginx:
    container_name: servermanager
    networks:
      nginx_default:
    image: nginx
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../SummonerExpert-Client/nginx.conf:/etc/nginx/sites-enabled/summonerexpert-client.conf
      - ../SupermarKit/nginx.conf:/etc/nginx/sites-enabled/supermarkit.conf
      - ../danReynolds.ca/nginx.conf:/etc/nginx/sites-enabled/danreynolds.conf
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/certs/dhparam.pem
      - letsencrypt:/etc/nginx/letsencrypt
      - webroot:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
volumes:
  webroot:
  letsencrypt:
  logs:
networks:
  nginx_default:
    external: true
